development:
  adapter: mysql2
  pool: 5
  host: 127.0.0.1
  username: root
  password: 
  database: teachME
    
    
test:
  adapter: mysql2
  pool: 5
  host: 
  username: 
  password: 
  database: teachME
    
production:
  adapter: mysql2
  pool: 5
  host: 
  username: 
  password: 
  database: teachME

